install: true

script:
  - git ls-remote
  - git config user.name
  - git config user.email
  - echo "after printed git account"
  - build_head=$(git rev-parse HEAD)
  - echo $build_head
  - echo $TRAVIS_BRANCH
  - git diff $build_head $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - objBranch=$TRAVIS_BRANCH
  -  |
     if [ ${TRAVIS_PULL_REQUEST} != false ]; then
       objBranch=${TRAVIS_PULL_REQUEST_BRANCH}
     fi
  - echo $objBranch
  - git clone --dept=50 https://github.com/triasteam/iri-regression-tests.git ./iri-regression-tests/
  - cd iri-regression-tests
  - branchCount=(`git ls-remote | grep -Ec '${TRAVIS_PULL_REQUEST_BRANCH}'`)
  - echo '$TRAVIS_PULL_REQUEST_BRANCH count is : ', $branchCount
  -  |
     if [ $branchCount > 0 ]; then
       git checkout ${TRAVIS_PULL_REQUEST_BRANCH}
       git checkout master
       git merge ${TRAVIS_PULL_REQUEST_BRANCH}
     fi
  -  |
     if [ $branchCount == 0 ]; then
       git checkout master
     fi
  - git branch  
