script:
  - git ls-remote
  - git config user.name
  - git config user.email
  - echo "after printed git account"
  - build_head=$(git rev-parse HEAD)
  - echo $build_head
  - echo $TRAVIS_BRANCH
  - git diff $build_head $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - GET repo/jdyuankai/branch/$TRAVIS_PULL_REQUEST_BRANCH
