install: true

script:
  - git ls-remote
  - git config user.name
  - git config user.email
  - echo "after printed git account"
  - build_head=$(git rev-parse HEAD)
  - echo $build_head
  - echo $TRAVIS_BRANCH
  - git diff $build_head $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - content=(GET repo/jdyuankai/branch/$TRAVIS_PULL_REQUEST_BRANCH)
  - echo content
  - GET repo/jdyuankai/branch/{$TRAVIS_PULL_REQUEST_BRANCH}
  - GET repo/{repository.id}/branch/{branch.name}
  - echo $test_branch
  - command=(if [[ $TRAVIS_PULL_REQUEST == false ]] return $TRAVIS_BRANCH elif return $TRAVIS_PULL_REQUEST_BRANCH)
  -  |
     if [ ${TRAVIS_PULL_REQUEST} == false ]; then
       echo "do script"
     fi
    
